### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by taruch** [CiscoDevNet/Cat9kEVPN-Ansible#1]
https://github.com/CiscoDevNet/Cat9kEVPN-Ansible/blob/main/lab_guide.md#ansible-folder-for-design-based-playbooks
[Cat9k BGP EVPN Solution based Ansible Playbooks](https://github.com/jbogarin/bgp-evpn-ansible)

This is a broken link - gives a 404 error.

**Comment by jeremycohoe** [comment]
@raajkumargoli for lab_guide.md

**Comment by raajkumargoli** [comment]
@taruch , the link has been updated.
